<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */
    const DESCPROD = 'Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est. </p><p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.';

    public function run() {

        DB::table('category')->insert([
            ['catId' => 1, 'name' => 'Computer'],
            ['catId' => 2, 'name' => 'Telefonia'],
            ['catId' => 3, 'name' => 'Elettrodomestici']
        ]);

        DB::table('subcategory')->insert([
            ['subCatId' => 1, 'name' => 'NoteBook', 'catId' => 1],
            ['subCatId' => 2, 'name' => 'MacBook', 'catId' => 1],
            ['subCatId' => 3, 'name' => 'PC Desktop', 'catId' => 1],
            ['subCatId' => 4, 'name' => 'Smartphone Android', 'catId' => 2],
            ['subCatId' => 5, 'name' => 'Iphone', 'catId' => 2],
            ['subCatId' => 6, 'name' => 'Telefonia fissa', 'catId' => 2],
            ['subCatId' => 7, 'name' => 'Lavatrici', 'catId' => 3],
            ['subCatId' => 8, 'name' => 'Lavastoviglie', 'catId' => 3],
            ['subCatId' => 9, 'name' => 'Frigoriferi', 'catId' => 3]
        ]);

        DB::table('product')->insert([
            ['name' => 'LENOVO Ideapad S145-15API', 'subCatId' => 1,
                'price' => 449.00, 'discountPerc' => 12, 'image' => 'lenovo.png',
                'descShort' => 'Notebook da 15,6". LENOVO',
                'descLong' => 'Notebook IdeaPad S145-15API con Processore : AMD Ryzen 3 3200U Dual Core, 2.6 GHz frequenza turbo massima 3.5 GHz. Ram : 8 GB, 4GB Soldered DDR4-2400 + 4GB SO-DIMM DDR4-2400. Storage : 256 GB SSD M. 2 2242 PCIe 3.0x2 NVMe. Scheda grafica integrata : AMD Radeon Vega 3 Graphics. Fotocamera frontale 0.3Mp. Connettività: 11ac, 1x1 + BT4.2. Porte: 1x USB 2.0, 2x USB 3.1 Gen 1, 1x HDMI, Jack combinato per microfono / auricolare. Sistema operativo : Windows 10 Home, 64 bit. Monitor da 15.6" LED con risoluzione 1920 x 1080 Pixel Full HD. Bateria Ioni di Litio (Li-Ion) con capacità della batteria 30 Wh. Durata della Batteria 4 Ore.'],
            ['name' => 'ACER Aspire 3 A315-55G-5364', 'subCatId' => 1,
                'price' => 699.00, 'discountPerc' => 12, 'image' => 'acernotebook.png',
                'descShort' => 'Notebook da 15,6". ACER',
                'descLong' => 'Notebook Aspire 3 A315-55G con Processore : Intel Core i7-10510U Quad Core, 1.8 GHz. Ram : 16 GB, DDR4 SDRAM. Storage : 512 GB SSD (Solid State Disk). Scheda grafica dedicata : Nvidia GeForce MX230 con 2 GB di memoria dedicata. Acer Crystal Eye HD webcam. Connettività Wireless LAN IEEE 802.11ac e Bluetooth 4.2. Porte: 1x USB 2.0, 2x USB 3.1 Gen 1 di tipo A, Ethernet LAN (RJ-45). Sistema operativo : Windows 10 Home, 64 bit. Monitor da 15.6" LED con risoluzione 1920x1080 Full HD.'],
            ['name' => 'ASUS TC-886', 'subCatId' => 1,
                'price' => 329.00, 'discountPerc' => 12, 'image' => 'asus.png',
                'descShort' => 'Notebook da 15,6". ASUS',
                'descLong' => 'Processore : Intel Core i7-7820HK Hexa Core, 2.2 GHz frequenza turbo massima 4.1 GHz. Ram : 16 GB, DDR4-SDRAM. Storage : 1 TB HDD (Hard Disk Drive), e 512 GB SSD (Solid State Disk). Scheda grafica dedicata : Nvidia GeForce GTX 1050 con 4 GB di memoria dedicata. Fotocamera frontale HD 720p con risoluzione 1280 x 720 pixel. Connettività Wireless LAN 802.11a, 802.11b, 802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac) e Bluetooth 4.2. Porte: 1x USB 3.0 (3.1 Gen 1) Tipo-A, 1x USB 3.0 (3.1 Gen 1) Tipo C, 2x USB 2.0, 1x HDMI, 1x Ethernet LAN (RJ-45). Sistema operativo : Windows 10 Home, 64 bit. Monitor da 15.6" LED con risoluzione 1920x1080 Full HD. Tastiera retroilluminata. Bateria Polimero di litio (LiPo) a 3 celle con capacità della batteria 47 Wh.'],
            ['name' => 'APPLE MacBook Pro 13" 128 Gb 2019', 'subCatId' => 2,
                'price' => 1549.00, 'discountPerc' => 15, 'image' => 'pro13.png',
                'descShort' => 'Notebook da 13,3". APPLE',
                'descLong' => 'MacBook Pro Monitor con Processore : Intel Core i5-8257U Quad Core, 1.4 GHz frequenza turbo massima 3.9 GHz. Ram : 8 GB, LPDDR3-SDRAM. Storage : 256 GB SSD (Solid State Disk). Scheda grafica integrata : Intel Iris Plus Graphics 645. Fotocamera frontale da 720p. Connettività Wireless Wi-Fi 5 (802.11ac) e Bluetooth 5.0. Porte USB : 2 x 3 Thunderbolt, 1 x Uscite per cuffie, 1 x Jack combinato per microfono / auricolare. Sistema operativo : MacOS Mojave. Monitor da 13,3" IPS con risoluzione 2560 x 1600 WQXGA. Tastiera retroilluminata. Bateria Polimero di litio (LiPo) con capacità della batteria 58 Wh. Durata della Batteria 10 Ore.'],
            ['name' => 'APPLE iMac 21.5" MMQA2T/A 2017', 'subCatId' => 2,
                'price' => 1349.00, 'discountPerc' => 15, 'image' => '21.5.png',
                'descShort' => 'PC All-In-One. APPLE',
                'descLong' => 'iMac con Processore : Intel Core i5 Dual Core a 2,3 GHz (Turbo Boost fino a 3,6 GHz). Memoria : 8 GB di memoria DDR4 a 2133MHz su scheda. Storage : HDD da 1TB a 5400 giri / min. Scheda grafica : Intel Iris Plus Graphics 640. Videocamera FaceTime HD integrata. Porte USB 3.0 (compatibili con USB 2.0) x 4. Porte Thunderbolt 3 x 2. Connessioni Wi-Fi 802.11ac e Tecnologia wireless Bluetooth 4.2. Sistema operativo : MacOS Sierra. Monitor retroilluminato LED da 21,5" (diagonale) con risoluzione 1920×1080.'],
            ['name' => 'APPLE iMac 4k 21.5" 6Core MRT42T/A 2019', 'subCatId' => 2,
                'price' => 1749.00, 'discountPerc' => 15, 'image' => '4k21.5.png',
                'descShort' => 'All in One. APPLE',
                'descLong' => 'iMac con Processore : Intel Core i5 Hexa Core a 3 GHz (Turbo Boost fino a 4.1 GHz). Ram : 8GB di memoria DDR4-SDRAM a 2666 MHz su scheda. Storage : Fusion Drive 1 TB. Scheda dedicata : AMD Radeon Pro 560X 4GB. Fotocamera integrata. Connessione in rete Wi-Fi 802.11a, Wi-Fi 5 (802.11ac), 802.11b, 802.11g, Wi-Fi 4 (802.11n) e Bluetooth 4.2. Porta: 4x USB 3.0 (3.1 Gen 1) di tipo A, 1x Ethernet LAN (RJ-45), 2x Thunderbolt 3, 1x Uscite per cuffie. Sistema operativo : macOS Mojave 10.14. Display retina retroilluminato LED da 21.5" 4096 x 2304. Colore del prodotto : Argento.'],
            ['name' => 'MSI TRIDENT 3 E21G-19A14', 'subCatId' => 3,
                'price' => 1099.00, 'discountPerc' => 15, 'image' => 'msitrident.png',
                'descShort' => 'PC Desktop. MSI',
                'descLong' => 'Processore : Intel Core i7-9700F (frequenza base 3,0 GHz, fino a 4,7 GHz, 12 MB di cache, Octa Core). Ram : 8 GB di SDRAM DDR4- 2666 MHz. Storage : SSD (Solid State Drive) da 1 TB. Scheda grafica dedicata : NVIDIA GeForce RTX 2060 Super (8 GB di GDDR6 dedicata). Connettività Wireless LAN : Wi-Fi 5 (802.11ac) e Bluetooth 5.0. Interfaccia di rete : LAN Gigabit Ethernet 10/100/1000 integrata. Porte USB : 2 x USB 3.1 (3.1 Gen 2) di tipo A, 2 x USB 3.0 (3.1 Gen 1) di tipo A, 2 x USB 2.0, 1 x Ethernet LAN (RJ-45), 1 x DisplayPorts, 1 x Uscite per cuffie. Sistema operativo : Windows 10 Home, 64 bit.'],
            ['name' => 'ACER  S91315-NE91100', 'subCatId' => 3,
                'price' => 899.00, 'discountPerc' => 15, 'image' => 'acerpcdesk.png',
                'descShort' => 'PC Desktop. ACER',
                'descLong' => 'Processore: Intel Core i5-9400 (frequenza base 2.9 GHz, 9 MB di cache, Hexa Core). Ram: 8 GB di DDR4-SDRAM-2133 (1 x 8 GB). Ram massima supportata: 32 GB. Storage: HDD (Hard Disk Drive) SATA da 1 TB (7200 rpm). Scheda grafica integrata: Intel UHD Graphics 630. Interfaccia di rete: LAN Ethernet 10/100/1000 integrata. Porte: 4x USB 2.0, 4x USB 3.2 Gen 1 (3.1 Gen 1) di tipo A, 1x VGA, 1x Ethernet LAN (RJ-45), 1x HDMI. Sistema operativo: Windows 10 Pro, 64 bit. Alimentazione 180 W.'],
            ['name' => 'HP PAVILION TP01-0108NL', 'subCatId' => 3,
                'price' => 699.00, 'discountPerc' => 15, 'image' => 'hp.png',
                'descShort' => 'PC Desktop. HP',
                'descLong' => 'Processore Intel Core i5-9400F (frequenza base 2.9 GHz, fino a 4.1 GHz, 9 MB di cache, Hexa Core). Ram: 8 GB di DDR4-SDRAM-2666 (1 x 8 GB). Storage: SSD (Solid State Drive) PCI Express da 256 GB. Scheda grafica dedicata: NVIDIA GeForce GT 1030 (2 GB di GDDR5 dedicata). Connettività Wireless LAN: 802.11a, 802.11b, 802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac) (1x1) e Bluetooth 4.2. Interfaccia di rete: LAN Gigabit Ethernet 10/100/1000 integrata. Porte: 4x USB 2.0, DVI, 1x Ethernet LAN (RJ-45). Sistema operativo: Windows 10 Home, 64 bit. Alimentazione 180 W.'],
            ['name' => 'SAMSUNG Galaxy A71 Black', 'subCatId' => 4,
                'price' => 479.00, 'discountPerc' => 15, 'image' => 'galaxyA71.png',
                'descShort' => 'Smartphone Dual SIM. Samsung',
                'descLong' => 'Samsung Galaxy A71 è uno smartphone Android avanzato e completo sotto tutti i punti di vista con alcune eccellenze. Dispone di un grande display da 6.7 pollici con una risoluzione di 2400x1080 pixel. Le funzionalità offerte da questo Samsung Galaxy A71 sono veramente tante e avanzate. A cominciare dal modulo LTE 4G che permette un trasferimento dati e una navigazione in internet eccellente. Questo Samsung Galaxy A71 è un prodotto con pochi competitor per ciò che riguarda la multimedialità grazie alla fotocamera da ben 64 megapixel che permette al Samsung Galaxy A71 di scattare foto di alta qualità con una risoluzione di 9238x6928 pixel e di registrare video in 4K alla risoluzione di 3840x2160 pixel. Lo spessore di 7.7mm è veramente contenuto e rende questo Samsung Galaxy A71 ancora più spettacolare.'],
            ['name' => 'XIAOMI Redmi 8 64GB Black TRE', 'subCatId' => 4,
                'price' => 169.99, 'discountPerc' => 15, 'image' => 'readmi8.png',
                'descShort' => 'Smartphone Dual SIM. Xiaomi',
                'descLong' => 'Xiaomi Redmi Note 8 Pro. Display FHD+ a goccia da 6.53". Luce blu ridotta. Schermo certificato TÜV Rheinland. Corning Gorilla Glass 5 anteriore e posteriore. Ridotta la possibilità di danniallo schermo dovuti a caduta. Quad Camera da 64 MP. Processore da gaming con tecnologia di raffreddamento a liquido. Foto ad alta risoluzione per stampe di poster alte fino a 3.26 m. Obiettivo macro per primi piani da 2 cm. Autofocus a distanza super ravvicinata. Correzione della distorsione ultra-grandangolare a 120°. Cattura paesaggio in un solo scatto. Selfie Camera da 20MP Modalità ritratto AI con regolazione della sfocatura dello sfondo. Processore gaming Helio G90T Architettura Cortex-A76. Prestazioni migliorate rispetto a Snapdragon 710. Potenti prestazioni della GPU. Gioca ad alta intensità con un frame rate elevato a lungo. Batteria da 4500 mAh e supporto per ricarica rapida a 18W. Estetica e materiali premium Retro incurvato su 4 lati 91.4% rapporto schermo-corpo. NFC multifunzionale. Trasforma il tuo telefono in un portafogli. 6 GB di RAM. Lo spessore di 8.8 mm è contenuto e rende questo Redmi Note 8 Pro molto interessante. Colore grigio.'],
            ['name' => 'HUAWEI P40 Lite Black', 'subCatId' => 4,
                'price' => 299.99, 'discountPerc' => 15, 'image' => 'p40Lite.png',
                'descShort' => 'Smartphone Dual SIM. Huawei',
                'descLong' => 'Huawei P40 Lite è uno smartphone Android avanzato e completo sotto tutti i punti di vista con alcune eccellenze. Dispone di un grande display da 6.4 pollici con una risoluzione di 1080 x 2310 pixel. Le funzionalità offerte da questo Huawei P40 Lite sono veramente tante e avanzate. Huawei P40 Lite è un prodotto con pochi competitor per ciò che riguarda la multimedialità grazie alla fotocamera da ben 48 megapixel che permette al Huawei P40 Lite di scattare foto di alta qualità con una risoluzione di 8000x6000 pixel e di registrare video in alta definizione alla risoluzione di 1920x1080 pixel. Lo spessore di 8.7mm è veramente contenuto e rende questo Huawei P40 Lite ancora più spettacolare.'],
            ['name' => 'APPLE iPhone 15 Pro 64GB Oro', 'subCatId' => 5,
                'price' => 1189.00, 'discountPerc' => 15, 'image' => '11pro.png',
                'descShort' => 'Smartphone. APPLE',
                'descLong' => 'La perfetta quantità di tutto. Un nuovo sistema a doppia fotocamera, per inquadrare più cose intorno a te. Il chip per smart­phone più veloce che ci sia, insieme a una batteria che ti dà una giornata intera di libertà, per fare più cose ancora più a lungo. E la più alta qualità video mai raggiunta da uno smart­phone, per ricordi più belli che mai. Un sistema a doppia fotocamera tutto nuovo. Passa dal grandangolo all’ultra-grandangolo e trova l’inquadratura perfetta per tutte le tue foto. Grandangolo da 12MP: Il nuovo sensore grandangolare ha il 100% di Focus Pixels, per un autofocus fino a tre volte più veloce quando c’è poca luce. Ultra-grandangolo da 12MP: L’inquadratura 4 volte più ampia è l’ideale per panorami, monumenti, gruppi, interni spaziosi e soggetti in movimento. Filma e monta con la qualità video più alta su uno smartphone. Entrambe le fotocamere di iPhone 15 ti danno video 4K a 60 fps incredibilmente nitidi. Arriva lo slofie, il selfie in slow-motion. A 120 fotogrammi al secondo tutto sembra più speciale, anche un ciao con la mano o una chioma scompigliata dal vento. E con la nuova fotocamera TrueDepth da 12MP puoi dare ancora più spazio ai tuoi selfie. iPhone 15 è resistente all’acqua fino a 2 metri per 30 minuti. Sia il vetro frontale che quello posteriore sono rinforzati attraverso un processo a doppio scambio ionico. LCD Liquid Retina. Tutto quel che vedi sul display all-screen è spettacolare e fedelissimo all’originale. iPhone 15 ha il chip per smartphone più veloce che ci sia. Il chip A13 Bionic mette il turbo a tutto quello che fai. Ed è anche superefficiente, così la batteria dura più a lungo. Non è solo evoluto: è anni luce avanti agli altri.'],
            ['name' => 'APPLE iPhone Xj 128GB Black', 'subCatId' => 5,
                'price' => 789.00, 'discountPerc' => 15, 'image' => 'xj.png',
                'descShort' => 'Smartphone. APPLE',
                'descLong' => 'Ram 4 GB e Storage 64 GB, Display multi-touch OLED 5,8" Super Retina in due formati, fra cui il display più grande mai visto su un iPhone. Face ID sempre più veloce. Il chip per smartphone più potente e intelligente che ci sia. E un rivoluzionario sistema a doppia fotocamera. iPhone XS ha tutto quello che ami in un iPhone, pensato ancora più in grande. Ricarica wireless. Grazie alla superficie posteriore in vetro iPhone XS si ricarica senza cavo, Face ID evoluto. Tenere i tuoi dati al sicuro è facile, quando la tua password è il tuo volto: per sbloccare l’iPhone, fare login nelle app e pagare i tuoi acquisti ti basta uno sguardo. Doppia fotocamera posteriore da 12MP ƒ / 1.8, grandangolo ƒ / 2.4, teleobiettivo, Sensore 2x più veloce per scattare sempre in Smart HDR. Modalità Ritratto con Controllo profondità, Video 4K fino a 60 fps, Fotocamera TrueDepth ƒ / 2.2 grandangolo. Modalità Ritratto con Controllo profondità, Video 1080p, fino a 60 fps, SIRI Per mandare messaggi, impostare promemoria e molto altro, usando la voce, Suggeri­menti smart sulla schermata di blocco e in Messaggi, Mail, QuickType e altro, Attivazione vocale con il comando “Ehi Siri.'],
            ['name' => 'APPLE iPhone ES 128GB RED', 'subCatId' => 5,
                'price' => 549.00, 'discountPerc' => 15, 'image' => 'se.png',
                'descShort' => 'Smartphone. APPLE',
                'descLong' => 'Proprio quello che vuoi. A meno di quello che pensi. iPhone SE 2, il telefono da 4.7" più potente di sempre. La fotocamera è una 12 megapixel con stabilizzatore ottico, apertura f / 1.8 ed ottica grandangolare in grado di registrare video in risoluzione massima 4K a 60fps con audio stereo. La fotocamera anteriore ha un sensore da 7 megapixel con apertura f / 2.2. Su entrambe le fotocamere è presente la modalità ritratto. Display IPS da 4.7 pollici in rapporto 16:9 con risoluzione di 1334×750 pixel a 326 ppi, Touch ID per lo sblocco tramite il riconoscimento delle impronte e ricarica wireless per la batteria. iPhone SE ha lo stesso, straordinario chip di iPhone 11 Pro: si chiama A13 Bionic, ed è il più veloce mai visto su uno smart­phone. Tutto è incredibilmente fluido quando apri le app, ti lanci nei videogiochi e scopri nuovi modi di lavorare e divertirti con la realtà aumentata. Lo spettacolo deve continuare. E anche a lungo: con iPhone SE puoi guardare fino a 13 ore di video con una sola carica. Probabilmente ti stancherai prima tu, ma in caso di emergenza ti basta appoggiare il telefono su una base di ricarica wireless. Oppure puoi usare un alimentatore da 18W compatibile con la ricarica veloce per riportare la batteria da zero al 50% in appena 30 minuti. Progettato per iOS 13. E oltre. Con iPhone SE hai tutte le funzioni più recenti di iOS, e anche quelle che verranno. Puoi già goderti la Modalità scura, i comandi rapidi di Siri e la nuova app Foto, e in futuro potrai approfittare delle ultime novità in fatto di funzioni e sicurezza. Due SIM, due numeri. Grazie alla dual SIM con tecnologia eSIM puoi usare il tuo numero personale e quello di lavoro sullo stesso iPhone.'],
            ['name' => 'GIGASET A270 Black', 'subCatId' => 6,
                'price' => 19.99, 'discountPerc' => 15, 'image' => 'gigaset.png',
                'descShort' => 'Telefono cordless. GIGASET',
                'descLong' => 'Brillante qualità del suono HSP. 2 tasti funzione per accesso diretto alle tue funzioni preferite (possono essere settati individualmente). Modalità giorno / notte selezionabili per silenziare la suoneria del telefono. Ampia durata della batteria sia in conversazione che in standby (14 e 300h rispettivamente). Ergonomico e preciso keypad costituito da materiali di alta qualità. Supporta il Gigaset L410 hands-free clip. Puoi aggiungere fino a un massimo di 5 handset, per un totale di 6. Segreteria telefonica personalizzabile con una durata fino a 30 minuti.'],
            ['name' => 'BRONDI Bravo Style Nero', 'subCatId' => 6,
                'price' => 44.99, 'discountPerc' => 15, 'image' => 'brondi.png',
                'descShort' => 'cordless per anziani, con tasti grandi. BRONDI',
                'descLong' => 'Brondi Gala Twin. Tipo: Telefono DECT, Tipo di apparecchio: Cornetta wireless, Raggio di azione interno: 50 m, Raggio di azione esterno: 300 m. Capacità rubrica: 20 voci. Identificatore di chiamata. Colore del prodotto: Nero. Numero di cornette incluse: 2'],
            ['name' => 'MOTOROLA T301 Plus Nero', 'subCatId' => 6,
                'price' => 24.99, 'discountPerc' => 15, 'image' => 'motorola.png',
                'descShort' => 'Telefoni Cordless. MOTOROLA',
                'descLong' => 'telefono cordless dotato di display retroilluminato, con funzioni base come ad esempio il vivavoce di semplice utilizzo. Ampio display alfanumerico retroilluminato. Identificazione del chiamante CLIP. Vivavoce. Rubrica: 100 nomi e numeri. Funzione BIS: riselezione degli ultimi 10 numeri chiamati. Registro chiamate: ultime 50. Autonomia: 100h in standy / 10h in conversazione. Tasto mute. Blocco tramite codice PIN a 4 cifre. 10 suonerie di cui 8 polifoniche. Regolazione del volume su 5 livelli. Blocco tasti. Funzione allarme. Allarme batterie scariche. Fino a 4 basi e 5 ricevitori per base.'],
            ['name' => 'ELECTROLUX SE1879O-BLY120', 'subCatId' => 7,
                'price' => 459.00, 'discountPerc' => 15, 'image' => 'electrolux.png',
                'descShort' => 'Lavatrice Slim. Electrolux',
                'descLong' => 'La lavatrice compatta PerfectCare 600 con sistema SensiCare regola la durata del programma a seconda delle dimensioni del carico, usando meno energia e acqua ed evitando lavaggi troppo lunghi. In questo modo è possibile effettuare un ciclo economico anche con i carichi più piccoli. Il design compatto permette di risparmiare spazio senza scendere a compromessi in capacità o cura dei capi. Opzione SoftPlus per preparare al meglio i tuoi capi al lavaggio. Opzione Vapore AntiAllergy combina il vapore acqueo con un programma di lavaggio ad alte prestazioni per eliminare i batteri dagli indumenti. La nostra funzione Eco Time Manager vi consente di regolare la durata del ciclo di lavaggio in base al tempo che avete a disposizione. Ciò vi consente di risparmiare tempo ed energia. Mantieni perfetti i tuoi capi grazie alla lavatrice compatta di Electrolux. Il design salvaspazio flessibile permette di inserire la lavatrice in aree troppo ristrette per unità di dimensioni standard. Ad ogni lavaggio ottieni fantastici risultati senza compromettere i tuoi capi preferiti. Classe di efficienza energetica A+++-10%. Dimensioni: 845 x 595 x 450 mm. Colore del prodotto bianco.'],
            ['name' => 'HOOVER DXOC34 26C32-01', 'subCatId' => 7,
                'price' => 549.00, 'discountPerc' => 15, 'image' => 'hoover.png',
                'descShort' => 'Lavatrice Slim. Hoover',
                'descLong' => 'Hoover Dynamic Next rappresenta un vero cambiamento nel mondo della lavabiancheria. Il perfetto connubio tra stile e tecnologia che ti permette di ottenere il lavaggio perfetto per te. Testa una vera forte efficienza. Dynamic Next One Touch ti permette di lavare a pieno carico, colori e tessuti differenti insieme, in lavaggi rapidi e a basse temperature. Risparmiando su tutti i fronti, grazie alla Tecnologia All in One. Puoi scegliere tra diverse combinazioni di comandi (Full Touch o manopola) e Display (Digital, Touch o LCD Touch), per selezionare il tuo modello ideale. Il display full touch è perfetto per un utilizzo più veloce e intuitivo. Classe efficienza energetica: A+++. Dimensione: Larghezza: 600 mm, Profondità: 400 mm, Altezza: 850 mm. Colore del prodotto Bianco.'],
            ['name' => 'INDESIT BWA 71053X W IT', 'subCatId' => 7,
                'price' => 679.00, 'discountPerc' => 15, 'image' => 'indesit.png',
                'descShort' => 'Lavatrice carica frontale. Indesit',
                'descLong' => 'Installazione: Libera installazione. Colore del prodotto: Bianco. Display incorporato: Si. Tipo di display: LCD. Cerniera porta: Sinistra. Capacità cestello: 7 kg. Velocità di centrifuga massima: 1200 Giri / min. Classe efficienza energetica: A+++. Consumo energetico annuale: 174 kWh. Consumo di energia per lavaggio: 1,005 kWh. Consumi (modalità stand-by) : 8 W. Consumi (modalità spento) : 0,5 W. Consumo annuale di acqua: 8770 L. Classe di efficienza della centrifuga: B. Umidità residua: 53%. Ciclo: 215 min. Emissione acustica: 58 dB. Silenziosità (centrifuga) : 80 dB. Partenza differita: Si. Quantità programmi di lavaggio: 13. Programmi di lavaggio: Programma lavaggio eco, sport, intensivo, jeans, lavaggio a mano / lana, lavaggio delicati / seta, misti, cotone, sintetici. Altezza 85 cm, Larghezza 59,5 cm, Profondità 51,7 cm.'],
            ['name' => 'BOSCH SMS46KI01E', 'subCatId' => 8,
                'price' => 599.00, 'discountPerc' => 15, 'image' => 'bosch.png',
                'descShort' => 'Lavastoviglie. Bosch',
                'descLong' => 'Lavastoviglie a libera installazione con una classe energetica A++ che permette un notevole risparmio energetico pur mantenendo la massima efficienza, garantendo una grande riduzione dei consumi ed il massimo rispetto per l’ambiente. Colore bianco. L’EcoSilence Drive adegua la pressione dell’acqua sulle stoviglie lucentezza e risultati impeccabili. Il sistema AquaStop è formato da un tubo flessibile con alimentazione a doppia parete ed una valvola di sicurezza ed una vaschetta a pavimento che fornisce una protezione totale dagli eventuali danni provocati dall’acqua. Il cestello vario si posiziona nella parte inferiore fornendo uno spazio supplementare per le posate. L’activeWater ottimizza l’efficienza garantendo un lavaggio eco consentendo un notevole risparmio energetico e di acqua garantendo risultati eccellenti, tutto ciò si realizza grazie ad una distribuzione idrica mirata, rapido riscaldamento. e prestazioni superiori della pompa di calore per una circolazione perfetta dell’acqua. Il sensore di carico consente di risparmiare acqua ed energie in base al tipo di carico.'],
            ['name' => 'HOTPOINT ARISTON HFO 3C21 W C X', 'subCatId' => 8,
                'price' => 579.00, 'discountPerc' => 15, 'image' => '',
                'descShort' => 'Lavastoviglie. Ariston',
                'descLong' => 'Flexipower è un motore di nuova generazione ad elevata efficienza studiato per ottimizzare in ogni istante l’efficacia di lavaggio e variare velocità di funzionamento e pressione dell’acqua in base al tipo di sporco presente sulle stoviglie. Il nuovo sistema Dual-Space consente di sfruttare tutta l altezza del cesto inferiore per piatti e stoviglie particolarmente ingombranti: in un solo gesto il cesto superiore si solleva in modo semplice ed ergonomico. Installazione: Libera installazione, Colore della porta: Acciaio inossidabile, Dimensione: Full size (60 cm). Numero di coperti: 14 coperti, Emissione acustica: 42 dB, Classe efficacia di asciugatura: A. Classe efficienza energetica: A+++, Consumo di energia per ciclo: 0,9 kWh, Consumo di acqua per ciclo: 9 L. Larghezza: 600 mm, Profondità: 600 mm, Altezza: 850 mm.'],
            ['name' => 'WHIRLPOOL AN792149', 'subCatId' => 8,
                'price' => 669.00, 'discountPerc' => 15, 'image' => 'whirlpool.png',
                'descShort' => 'Lavastoviglie. Whirlpool',
                'descLong' => 'capacità 14 Coperti. TECNOLOGIA 6° SENSO Nessun prelavaggio necessario. La tecnologia garantisce risultati perfetti senza bisogno di pretrattare o lavare a mano, mentre riduce i costi di consumo dell acqua. Opzione Partenza Ritardata permette di scegliere un orario migliore in cui far partire il lavaggio una volta caricata la lavastoviglie. Ampliare, ridurre o adattare lo spazio interno della tua lavastoviglie a tuo piacimento grazie ai cestelli modulari e agli elementi flessibili. Il cestello superiore regolabile della tua lavastoviglie ti consente di creare tutto lo spazio di cui hai bisogno e ti permette di accomodare senza sforzo anche oggetti dalla forma irregolare. Questa lavastoviglie Whirlpool è dotata di un sistema di sicurezza antiallagamento integrato nel tubo di alimentazione, che impedisce la fuoriuscita di acqua in caso di guasto. Il mezzocarico intelligente che permette di scegliere dove effettuare il lavaggio. Multizona aumenterà automaticamente la forza dei getti di acqua sul cestello inferiore (+20%), assicurando risultati di lavaggio impareggiabili. Flexi Space. Nuovo design di pregio con uniformità di colore di tutti i cestelli e maniglia premium per un ottima estrazione del cestello. Classe energetica: A+++. Dimensioni prodotto (L x P x A) : 600 x 600 x 850 mm. Colore Acciaio Inox.'],
            ['name' => 'LG F11420AS51415R', 'subCatId' => 9,
                'price' => 999.00, 'discountPerc' => 7, 'image' => 'lg.png',
                'descShort' => 'Frigorifero combinato. LG',
                'descLong' => 'Il compressore lineare inverter LG contribuisce a mantenere l’aspetto e il sapore dei prodotti freschi più a lungo, riducendo le variazioni di temperatura. Raffreddamento uniforme 24 ore su 24. Le bocchette di ventilazione situate nella parte anteriore del frigorifero ristabiliscono più velocemente la temperatura ideale per conservare la freschezza degli alimenti. Il FRESH Balancer™ attraverso l’utilizzo dei selettori permette di mantenere sempre l’umidità ottimale per frutta e verdura in base alla modalità impostata. Il FRESH Converter™ permette di personalizzare la temperatura del cassetto 0 gradi per una migliore conservazione di carne, pesce e verdura. Il Wine Rack e il 2-Step Folding Shelf consentono di separare i diversi tipi di alimenti per una organizzazione pratica della cucina. Il 2-Step Folding Shelf permette di poggiare alimenti di qualsiasi dimensione e di creare spazio per contenitori alti e voluminosi. Classe energetica: A+++. Dimensioni prodotto (L x P x A) : 595 x 682 x 2030 mm. Colore Grigio.',],
            ['name' => 'SAMSUNG FE4518IC1', 'subCatId' => 9,
                'price' => 539.00, 'discountPerc' => 7, 'image' => 'samsung.png',
                'descShort' => 'Frigorifero doppia porta no frost. Samsung',
                'descLong' => 'Frigorifero a versione Total No Frost. La tecnologia Twin Cooling Plus è in grado di creare un ambiente favorevole per la conservazione dei cibi, In questo modo gli alimenti rimangono freschi più a lungo senza seccarsi. Il sistema Twin Cooling Plus grazie ai due circuiti indipendenti di circolazione evita la diffusione di odori indesiderati dal frigorifero al congelatore. Grazie alla funzione Smart Cooling è possibile trasformare con facilità il congelatore in un frigorifero per mantenere freschi tutti i cibi che devi conservare nelle varie stagioni o in occasioni speciali, oppure attivare la modalità OFF per risparmiare energia. Con la semplice click sul display, la funzione Power Cool raffredda i cibi e le bevande, mentre Power Freeze permette di surgelare e conservare i cibi e produrre ghiaccio. Il ripiano Easy Slide ti consente di conservare, organizzare e accedere ai cibi in maniera più comoda e flessibile, riuscendo a raggiungere facilmente anche ciò che si trova sul fondo. Il compressore Digital Inverter ha un dispositivo che modula la potenza erogata, in maniera proporzionale alle effettive necessità. risparmia energia e minimizza il rumore grazie al rivestimento fonoassorbente. La protezione antibatterica mantiene il frigo sempre pulito e igienico. Rispetto ai sistemi di illuminazione tradizionali, la luce a LED ad alta efficienza risulta più snella, accattivante e funzionale dal punto di vista energetico. Classe energetica: A++. Dimensioni prodotto (L x P x A) : 700 x 726 x 1785 mm. Colore Inox.',],
            ['name' => 'BEKO MAS19I-MI129N115', 'subCatId' => 9,
                'price' => 399.00, 'discountPerc' => 0, 'image' => 'beko.png',
                'descShort' => 'Frigorifero Combinato. Beko',
                'descLong' => 'Il frigorifero è dotato di sistema di raffreddamento statico e sbrinamento automatico della zona frigorifero. 4 ripiani in vetro, 4 balconcini sulla porta e rastrelliera portabottiglie cromata. Guarnizioni antibatteriche. Classe energetica A+, Capacità lorda totale 321 lt. , Capacità netta totale 295 lt. Dimensioni (AxLxP) 185 x 60 x 60 cm, Colore Bianco, maniglie ricavate nelle porte.']
        ]);

        DB::table('users')->insert([
            ['name' => 'nome', 'surname' => 'cognome', 'email' => 'clienteregistrato@qualcosa.com',
                'username' => 'useruser', 'password' => Hash::make('7iEiLQo4'), 'role' => 'user', 'created_at' => date("Y-m-d H:i:s"),   //la password viene generata criptando con l'algoritmo di hashing la stringa alexalex
                'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'nome', 'surname' => 'cognome', 'email' => 'membrostaff@qualcosa.com',
                'username' => 'staffstaff', 'password' => Hash::make('7iEiLQo4'), 'role' => 'staff', 'created_at' => date("Y-m-d H:i:s"),   //la password viene generata criptando con l'algoritmo di hashing la stringa alexalex
                'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'nome', 'surname' => 'cognome', 'email' => 'amministratore@qualcosa.com',
                'username' => 'adminadmin', 'password' => Hash::make('7iEiLQo4'), 'role' => 'admin','created_at' => date("Y-m-d H:i:s"),   //la password viene generata criptando con l'algoritmo di hashing la stringa alexalex
                'updated_at' => date("Y-m-d H:i:s")]
        ]);
    }

}
